name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # --- Detect what should run (unit tests, integration tests, lint) ---
  detect:
    name: Detect test/lint targets
    runs-on: ubuntu-latest
    outputs:
      has_unit: ${{ steps.probe.outputs.has_unit }}
      has_integration: ${{ steps.probe.outputs.has_integration }}
      has_precommit: ${{ steps.probe.outputs.has_precommit }}
    steps:
      - uses: actions/checkout@v4
      - id: probe
        shell: bash
        run: |
          set -euo pipefail

          # Paths in your repo
          UNIT_DIR="mutually_informed_networks/src/lib_mutual_information/tests"
          INTEG_DIR="$UNIT_DIR/integration"

          if compgen -G "$UNIT_DIR/**/*.py" > /dev/null || compgen -G "$UNIT_DIR/*.py" > /dev/null; then
            echo "has_unit=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_unit=false" >> "$GITHUB_OUTPUT"
          fi

          if compgen -G "$INTEG_DIR/**/*.py" > /dev/null || compgen -G "$INTEG_DIR/*.py" > /dev/null; then
            echo "has_integration=true" >> "$GITHUB_OUTPUT"
          else
            ec
