name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect:
    name: Detect test/lint targets
    runs-on: ubuntu-latest
    outputs:
      has_unit: ${{ steps.probe.outputs.has_unit }}
      has_integration: ${{ steps.probe.outputs.has_integration }}
      has_precommit: ${{ steps.probe.outputs.has_precommit }}
    steps:
      - uses: actions/checkout@v4

      - id: probe
        shell: bash
        run: |
          set -euo pipefail

          UNIT_DIR="mutually_informed_networks/src/lib_mutual_information/tests"
          INTEG_DIR="$UNIT_DIR/integration"

          # default values
          echo "has_unit=false" >> "$GITHUB_OUTPUT"
          echo "has_integration=false" >> "$GITHUB_OUTPUT"
          echo "has_precommit=false" >> "$GITHUB_OUTPUT"

          # unit tests: any *.py under UNIT_DIR
          if [ -d "$UNIT_DIR" ] && find "$UNIT_DIR" -type f -name '*.py' -print -quit | grep -q .; then
            echo "has_unit=true" >> "$GITHUB_OUTPUT"
          fi

          # integration tests: any *.py under INTEG_DIR
          if [ -d "$INTEG_DIR" ] && find "$INTEG_DIR" -type f -name '*.py' -print -quit | grep -q .; then
            echo "has_integration=true" >> "$GITHUB_OUTPUT"
          fi

          # pre-commit config present?
          if [ -f ".pre-commit-config.yaml" ]; then
            echo "has_precommit=true" >> "$GITHUB_OUTPUT"
          fi
